[package]
name = "vpk-parser"
version = "0.1.0"
authors = ["fallen4eyes"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5.0.1"
sorted-vec = "0.3.2"
md5 = "0.6.1"
